# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_all_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 301)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_text_programing = QtWidgets.QPushButton(self.centralwidget)
        self.Button_text_programing.setGeometry(QtCore.QRect(40, 140, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_text_programing.setFont(font)
        self.Button_text_programing.setObjectName("Button_text_programing")
        self.Button_spam_text = QtWidgets.QPushButton(self.centralwidget)
        self.Button_spam_text.setGeometry(QtCore.QRect(260, 90, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_spam_text.setFont(font)
        self.Button_spam_text.setObjectName("Button_spam_text")
        self.Button_QR = QtWidgets.QPushButton(self.centralwidget)
        self.Button_QR.setGeometry(QtCore.QRect(260, 140, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_QR.setFont(font)
        self.Button_QR.setObjectName("Button_QR")
        self.Button_auto_click = QtWidgets.QPushButton(self.centralwidget)
        self.Button_auto_click.setGeometry(QtCore.QRect(40, 90, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_auto_click.setFont(font)
        self.Button_auto_click.setObjectName("Button_auto_click")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(80, 0, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 505, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_text_programing.setText(_translate("MainWindow", "Text programing"))
        self.Button_spam_text.setText(_translate("MainWindow", "Spam Text"))
        self.Button_QR.setText(_translate("MainWindow", "Qr code - Gen"))
        self.Button_auto_click.setText(_translate("MainWindow", "Auto Click"))
        self.title.setText(_translate("MainWindow", "Tools all in 1 - by vudc006"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
